//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRAndPayroll
{
    using System;
    using System.Collections.Generic;
    
    public partial class Designation_Master
    {
        public int Designation_Id { get; set; }
        public string Designation_Name { get; set; }
        public Nullable<System.DateTime> DateTimeLastUpdated { get; set; }
        public Nullable<int> LastUpdateUserId { get; set; }
    }
}
