//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRAndPayroll
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.WebPages.Html;

    public partial class Salary_Formula
    {
        public int Entry_Id { get; set; }

        [DataType(DataType.Date)]
        [Required(ErrorMessage = "*")]
        [Display(Name = "Start Date")]
        //[DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> Start_Date { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "Basic")]
        public string Basic { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "HRA")]
        public string HRA { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "Conveyance Allowance")]
        public string Conveyance_Allowance { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "Medical Allowance")]
        public string Medical_Allowance { get; set; }

        [Display(Name = "Other Allowance")]
        public string Other_Allowance { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "EPF Limit")]
        public Nullable<int> EPF_Limit { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "EPF Employee Share")]
        public string EPF_Employee_Share { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "EPF Employer Share")]
        public string EPF_Employer_Share { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "EPF Applicable On")]
        public string EPF_Applicable_On { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "ESI Limit")]
        public Nullable<int> ESI_Limit { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "ESI Employee Share")]
        public string ESI_Employee_Share { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "ESI Employer Share")]
        public string ESI_Employer_Share { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "ESI Applicable On")]
        public string ESI_Applicable_On { get; set; }

        public Nullable<System.DateTime> DateTimeLastUpdated { get; set; }
        public Nullable<int> LastUpdateUserId { get; set; }

        //public List<SelectListItem> EmpList { get; set; }
        public List<Salary_Formula> myFormulae { get; set; }

    }
}
