//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRAndPayroll
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Salary_Master
    {
        public int Entry_Id { get; set; }
        
        public Nullable<System.DateTime> Entry_Date { get; set; }
                
        public Nullable<int> Employee_Id { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "Start Date")]
        public Nullable<System.DateTime> Start_Date { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "Salary Amount")]
        public Nullable<int> Salary_Amount { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "Next Due Date")]
        public Nullable<System.DateTime> Next_Due_Date { get; set; }

        public string Remarks { get; set; }
        public Nullable<System.DateTime> DateTimeLastUpdated { get; set; }
        public Nullable<int> LastUpdateUserId { get; set; }
    }
}
